#!/usr/bin/env python3
"""build_methods.py — refresh the machine-stamped facts in the living methods docs.

The bundle ships one reader-facing methods reference per scorecard component:

    docs/README.md                      — index of the four tiles
    docs/scorecard_methods.md           — the combiner (how tiles are assembled)
    metrics/<m>/METHODS.md              — one per live metric (lpv/proning/sat/sbt)

Each is HAND-WRITTEN prose EXCEPT the block between the markers

    <!-- AUTOGEN:START -->  ...  <!-- AUTOGEN:END -->

which this script rewrites from the single sources of truth.

MULTI-SITE: these docs are COMMITTED, shared code artifacts, so the AUTOGEN block holds only
**site-invariant DEFINITIONS** — thresholds, drug/mode category lists, eligibility toggles, the
`definition_version`, and the headline *definition* (its label/denominator) — read from the canonical
`definitions/<metric>.json` (or, for LPV, regex-scraped code constants). It deliberately does NOT stamp
any site-specific or volatile facts (current headline num/den, the `generated` timestamp, the git SHA,
site_id, or the per-site grain): those would churn the committed files on every run and differ per site.
The live per-site numbers already live in each tile feed and in `output/<site>/output_to_share/manifest.json`
— that is where a reader looks up "what was the number for site X", while these docs answer "how is it
defined". Because the block is definition-only, re-running on any site/machine is a no-op diff unless a
definition actually changed (which is a meaningful commit).

Reads only JSON definitions + tile feeds (for invariant metadata: title/label/note/definition_version) +
(regex-scrapes) LPV code constants — touches NO CLIF data, never the data_path. Output is re-asserted
PHI-free before writing.

Run:  .venv/bin/python docs/build_methods.py     (also runs at the end of
      refresh_scorecard.sh / run_bundle.sh, so docs refresh on every rebuild)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]        # bundle root (holds bundle_config.py)
DOCS = ROOT / "docs"
sys.path.insert(0, str(ROOT))
import bundle_config as _bc                        # multi-site config + output resolver

START = "<!-- AUTOGEN:START -->"
END = "<!-- AUTOGEN:END -->"
STAMP_NOTICE = ("*The block below is machine-generated by `docs/build_methods.py` from the shared "
                "`definitions/` + pipeline code — do not edit by hand; edits are overwritten on the next "
                "refresh. It holds only site-invariant **definitions**; current per-site numbers live in "
                "each tile feed + `output/<site>/output_to_share/manifest.json`.*")

PHI_FORBIDDEN = ("hospitalization_id", "patient_id")   # mirrors build_scorecard.py / the feed guard

# Definitional knobs live in the shared, versioned definitions/<metric>.json (site-independent);
# lpv's knobs are code constants (see LPV_CONSTANT_SOURCES).
CONFIG_PATH = {
    "proning": ROOT / "definitions/proning.json",
    "sat": ROOT / "definitions/sat.json",
    "sbt": ROOT / "definitions/sbt.json",
}

# Top-level config keys that are plumbing, not definitions — skipped in the knob table.
CONFIG_PLUMBING = {
    "site", "timezone", "primary_dataset", "secondary_dataset", "tables_in_use",
    "output_path", "metrics", "cohort", "unit_labels", "clif_data_path", "filetype",
    "clif_version", "scorecard_tiles",
}

# LPV keeps its definitional numbers as Python module constants (no config.json). Scrape these by
# regex — NEVER import (importing a stage triggers a config/data read). If a constant is renamed the
# generator emits "(see code)" rather than silently dropping it.
LPV_CONSTANT_SOURCES = [
    ("metrics/lpv/code/02_features.py", ["ADHERENCE_FRACTION", "VT_MAX_DEFAULT", "PLATEAU_MAX", "DP_MAX"]),
    ("metrics/lpv/code/02d_severity.py", ["PF_THRESHOLD", "SF_THRESHOLD", "SPO2_MAX_FOR_SF", "PEEP_MIN",
                                          "O2_FIO2_LOOKBACK"]),
    ("metrics/lpv/code/03_aggregate.py", ["VT_DEFAULT"]),   # dashboard Vt-slider initial position
    ("metrics/lpv/code/05_tile_feed.py", ["SCORECARD_VT_CUTOFF", "LPV_GOAL", "DEFINITION_VERSION"]),
]


# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------
def _load_json(path):
    try:
        return json.loads(Path(path).read_text())
    except (FileNotFoundError, TypeError):
        return None


def _fmt(v):
    """Render a scalar/list config value for a Markdown table cell."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "null"
    if isinstance(v, list):
        return ", ".join(_fmt(x) for x in v)
    return str(v)


def _flatten(d, prefix=""):
    """Flatten a nested config dict to [(dotted.path, rendered_value)], skipping `_comment_*`."""
    rows = []
    for k, v in d.items():
        if isinstance(k, str) and k.startswith("_comment"):
            continue
        path = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            rows.extend(_flatten(v, path))
        else:
            rows.append((path, _fmt(v)))
    return rows


def _md_table(header, rows):
    if not rows:
        return "_(none)_\n"
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out) + "\n"


def _lpv_constant_rows():
    rows = []
    for rel, names in LPV_CONSTANT_SOURCES:
        text = (ROOT / rel).read_text() if (ROOT / rel).exists() else ""
        for name in names:
            m = re.search(rf"^\s*{re.escape(name)}\s*=\s*([^\s#]+)", text, re.MULTILINE)
            val = m.group(1).strip().strip('"').strip("'") if m else "(see code)"
            rows.append((name, val, f"`{rel}`"))
    return rows


def _definition_version(metric, feeds):
    """Site-invariant definition_version: prefer the feed's provenance, else definitions/<m>.json,
    else (LPV) the scraped DEFINITION_VERSION constant."""
    feed = feeds.get(metric) or {}
    dv = (feed.get("provenance") or {}).get("definition_version")
    if dv:
        return dv
    cfg = _load_json(CONFIG_PATH.get(metric))
    if cfg and cfg.get("definition_version"):
        return cfg["definition_version"]
    if metric == "lpv":
        for name, val, _src in _lpv_constant_rows():
            if name == "DEFINITION_VERSION":
                return val
    return "—"


def _knob_section(metric):
    """Markdown for the definitional-knob table + any `_comment_*` doc strings (site-invariant)."""
    if metric == "lpv":
        rows = _lpv_constant_rows()
        return ("**Definitional constants** (LPV has no `config.json`; scraped from the pipeline code — "
                "the tile headline and the dashboard Vt-slider both open at Vt ≤ `SCORECARD_VT_CUTOFF` "
                "(= `VT_DEFAULT`); the stored per-day adherent status is classified at Vt ≤ "
                "`VT_MAX_DEFAULT`):\n\n"
                + _md_table(["Constant", "Value", "Source"], rows))

    cfg = _load_json(CONFIG_PATH[metric])
    if cfg is None:
        return "_definitions file not found — knobs unavailable._\n"

    comments = []
    for k, v in cfg.items():
        if isinstance(k, str) and k.startswith("_comment") and isinstance(v, str):
            comments.append(f"> **{k}** — {v}")

    rows = []
    for k, v in cfg.items():
        if k in CONFIG_PLUMBING or (isinstance(k, str) and k.startswith("_comment")):
            continue
        if isinstance(v, dict):
            rows.extend(_flatten(v, k))
        else:
            rows.append((k, _fmt(v)))
    rows = [(f"`{p}`", val) for p, val in rows]

    out = f"**Definitional parameters** (from `{CONFIG_PATH[metric].relative_to(ROOT)}`):\n\n"
    out += _md_table(["Parameter", "Value"], rows)
    if comments:
        out += "\n**Config documentation strings** (verbatim):\n\n" + "\n\n".join(comments) + "\n"
    return out


# ---------------------------------------------------------------------------
# per-metric AUTOGEN block — DEFINITIONS ONLY (site-invariant)
# ---------------------------------------------------------------------------
def metric_autogen(metric, feed, feeds):
    hl = feed.get("headline", {})
    lines = [STAMP_NOTICE, ""]
    lines.append(f"**Tile:** {feed.get('title', metric)} — {feed.get('subtitle', '')}  ")
    lines.append(f"**Drill-down:** `{feed.get('detail_href', '—')}`  ")
    dv = _definition_version(metric, feeds)
    goal = f" · goal line {100 * feed['goal']:.0f}%" if feed.get("goal") is not None else ""
    lines.append(f"**Definition version:** `{dv}`{goal}")
    lines.append("")
    lines.append("**Headline definition:** "
                 f"{hl.get('label', 'numerator')} — denominator: {hl.get('den_label', '—')} "
                 f"(unit = {hl.get('n_unit', '—')}). "
                 "_Current per-site value: see the tile feed / `output_to_share/manifest.json`._")
    if feed.get("segments"):
        seg = ", ".join(s.get("label", s.get("key", "?")) for s in feed["segments"])
        lines.append("")
        lines.append(f"**Segments reported:** {seg}")
    lines.append("")
    lines.append(_knob_section(metric))
    if feed.get("note"):
        # The scorecard tile shows a caveat note, but it can embed that site's coverage numbers
        # (e.g. proning/sat), so it is NOT stamped here (it would churn per site). The definitional
        # caveat lives in the hand-written "Caveats" section above; the per-site worded note is on
        # the scorecard tile + in the tile feed.
        lines.append("**Tile caveat:** a per-site caveat note is shown on the scorecard tile and stored "
                     "in the tile feed (`note`); it may quote that site's coverage figures. See the "
                     "hand-written Caveats section above for the site-invariant version.")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# index + scorecard-level AUTOGEN blocks — DEFINITIONS ONLY, canonical metric set
# ---------------------------------------------------------------------------
def index_autogen(metrics, feeds):
    rows = []
    for m in metrics:
        feed = feeds.get(m)
        title = feed.get("title", m) if feed else m
        rows.append((
            f"**{title}**",
            f"`{_definition_version(m, feeds)}`",
            f"[`metrics/{m}/METHODS.md`](../metrics/{m}/METHODS.md)",
        ))
    out = [STAMP_NOTICE, ""]
    out.append(_md_table(["Tile", "Definition version", "Methods doc"], rows))
    out.append("\n_Current headline numbers per site live in each tile feed + "
               "`output/<site>/output_to_share/manifest.json`._")
    return "\n".join(out).rstrip() + "\n"


def scorecard_autogen(metrics, feeds):
    lines = [STAMP_NOTICE, ""]
    lines.append("**Tile order (canonical):** " + ", ".join(f"`{m}`" for m in metrics))
    lines.append("")
    lines.append("**Enabled metrics are per-site** — read from `sites/<site>.json → enabled_metrics`; a "
                 "site omits any tile it can't support (the slot shows a \"Coming soon…\" placeholder).")
    lines.append("")
    lines.append("**Feed discovery (by convention):** for each enabled metric `<m>`, the combiner reads "
                 "`output/<site>/metrics/<m>/final/tile_feed_<m>.json` (`load_feed`, "
                 "`scorecard/build_scorecard.py`). There is no `scorecard_tiles` registry key.")
    lines.append("")
    lines.append("**Definition versions:**")
    lines.append("")
    lines.append(_md_table(["Metric", "Definition version"],
                           [(f"`{m}`", f"`{_definition_version(m, feeds)}`") for m in metrics]))
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# splice
# ---------------------------------------------------------------------------
def splice(path, block, stub_header):
    """Replace the text between the AUTOGEN markers in `path` with `block`.
    If the file is absent, create it from `stub_header` + the markers.
    Returns "created" | "updated" | "unchanged"."""
    path = Path(path)
    wrapped = f"{START}\n\n{block}\n{END}"
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(stub_header.rstrip() + "\n\n" + wrapped + "\n")
        return "created"

    text = path.read_text()
    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), wrapped, text, count=1, flags=re.DOTALL)
    else:
        new = text.rstrip() + "\n\n" + wrapped + "\n"
    if new == text:
        return "unchanged"
    path.write_text(new)
    return "updated"


def _stub(title, intro):
    return (f"# {title}\n\n{intro}\n\n"
            "> _Prose above the AUTOGEN block is hand-written; edit it freely. "
            "The stamped facts below refresh from the pipeline on every scorecard rebuild._\n")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main():
    site = _bc.active_site()
    enabled = _bc.enabled_metrics(site)
    if not enabled:
        print(f"[methods] no metrics enabled for site '{site}' — nothing to do", file=sys.stderr)
        return 1

    # Read feeds only for INVARIANT metadata (title/label/note/definition_version). We never stamp
    # their live numbers into the committed docs.
    feeds = {}
    for m in enabled:
        feed = _load_json(_bc.metric_output_dir(m, site) / "final" / f"tile_feed_{m}.json")
        if feed is not None:
            feeds[m] = feed

    targets = []  # (rel_path, abs_path, block, stub)

    # Per-metric docs: refresh only metrics with a feed present (their invariant metadata).
    for m in enabled:
        feed = feeds.get(m)
        if feed is None:
            print(f"[methods] {m}: tile feed missing — skipped (run its pipeline first)")
            continue
        stub = _stub(f"{feed.get('title', m)} — Methods",
                     f"Methods & data-dictionary reference for the **{feed.get('title', m)}** scorecard tile. "
                     "See the sibling `CLAUDE.md` for implementation detail.")
        targets.append((f"metrics/{m}/METHODS.md", ROOT / "metrics" / m / "METHODS.md",
                        metric_autogen(m, feed, feeds), stub))

    # Index + scorecard: use the CANONICAL metric set so the committed docs don't depend on which
    # subset this particular site built (keeps them site-invariant).
    canonical = list(_bc.ALL_METRICS)

    idx_stub = _stub("CLIF Ventilator QI Bundle — Methods Index",
                     "Living methods / data-dictionary reference for every component of the QI bundle "
                     "scorecard. Each tile has its own methods doc; the combiner has one too.\n\n"
                     "- Combiner: [`scorecard_methods.md`](scorecard_methods.md)\n"
                     "- Tile-feed contract: [`../contract/tile_feed_contract.md`](../contract/tile_feed_contract.md)")
    targets.append(("docs/README.md", DOCS / "README.md", index_autogen(canonical, feeds), idx_stub))

    sc_stub = _stub("Bundle Scorecard — Methods",
                    "How the bundle scorecard (`scorecard/build_scorecard.py`) assembles the per-metric "
                    "tiles, and its grain-fallback / unit-grouping rules.")
    targets.append(("docs/scorecard_methods.md", DOCS / "scorecard_methods.md",
                    scorecard_autogen(canonical, feeds), sc_stub))

    # PHI guard — vet the machine-generated blocks before writing.
    for rel, _abs, block, _tmpl in targets:
        hits = [s for s in PHI_FORBIDDEN if s in block]
        if hits:
            print(f"[methods] ABORT — PHI substring(s) {hits} in the generated block for {rel}",
                  file=sys.stderr)
            return 2

    print("[methods] refreshed living methods docs (definitions only — no per-run/per-site churn):")
    for rel, abs_path, block, stub in targets:
        status = splice(abs_path, block, stub)
        print(f"  {status:9} {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
