#!/usr/bin/env python3
"""build_methods.py — refresh the machine-stamped facts in the living methods docs.

The bundle ships one reader-facing methods reference per scorecard component:

    docs/README.md                      — index of the four tiles
    docs/scorecard_methods.md           — the combiner (how tiles are assembled)
    metrics/<m>/METHODS.md              — one per live metric (lpv/proning/sat/sbt)

Each of those files is HAND-WRITTEN prose EXCEPT the block between the markers

    <!-- AUTOGEN:START -->  ...  <!-- AUTOGEN:END -->

which this script rewrites from the single sources of truth so the specific
numbers can never silently drift from the pipeline:

  * the tile feed  metrics/<m>/output/final/tile_feed_<m>.json  — current
    headline num/den/rate, grain, note, and the provenance block
    (definition_version, code_version SHA, clif_version, generated, site_id);
  * the per-metric config.json  — definitional knobs (thresholds, drug/mode
    category lists, eligibility toggles, small-cell floor) + any `_comment_*`
    doc strings.  LPV has NO config.json, so its constants are regex-scraped
    (never imported) from its Python stages — see LPV_CONSTANT_SOURCES.

Determinism: the stamped facts use the feed's OWN `generated` timestamp, never
`datetime.now()`, so re-running without a data change is a no-op diff.

Reads only JSON config + tile feeds + (regex-scrapes) LPV code constants — it
touches NO CLIF data, and only definitional knobs are stamped (never the
data_path).  Output is re-asserted PHI-free before writing.

Run:  .venv/bin/python docs/build_methods.py     (also runs at the end of
      refresh_scorecard.sh / run_bundle.sh, so docs refresh on every rebuild)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]        # bundle root (shared config.json)
DOCS = ROOT / "docs"

START = "<!-- AUTOGEN:START -->"
END = "<!-- AUTOGEN:END -->"
STAMP_NOTICE = ("*The block below is machine-generated by `docs/build_methods.py` from the tile feed + "
                "config — do not edit by hand; edits are overwritten on the next refresh.*")

PHI_FORBIDDEN = ("hospitalization_id", "patient_id")   # mirrors build_scorecard.py / the feed guard

# Which config.json holds each metric's definitional knobs (proning nests its under config/).
CONFIG_PATH = {
    "proning": ROOT / "metrics/proning/config/config.json",
    "sat": ROOT / "metrics/sat/config.json",
    "sbt": ROOT / "metrics/sbt/config.json",
    # lpv has no config.json — see LPV_CONSTANT_SOURCES
}

# Top-level config keys that are plumbing, not definitions — skipped in the knob table.
CONFIG_PLUMBING = {
    "site", "timezone", "primary_dataset", "secondary_dataset", "tables_in_use",
    "output_path", "metrics", "cohort", "unit_labels", "clif_data_path", "filetype",
    "clif_version", "scorecard_tiles", "clif_version",
}

# LPV keeps its definitional numbers as Python module constants (no config.json). Scrape these by
# regex — NEVER import (importing a stage triggers a config/data read). If a constant is renamed the
# generator emits "(see code)" rather than silently dropping it.
LPV_CONSTANT_SOURCES = [
    ("metrics/lpv/code/02_features.py", ["ADHERENCE_FRACTION", "VT_MAX_DEFAULT", "PLATEAU_MAX", "DP_MAX"]),
    ("metrics/lpv/code/02d_severity.py", ["PF_THRESHOLD", "SF_THRESHOLD", "SPO2_MAX_FOR_SF", "PEEP_MIN",
                                          "O2_FIO2_LOOKBACK"]),
    ("metrics/lpv/code/05_tile_feed.py", ["SCORECARD_VT_CUTOFF", "LPV_GOAL", "DEFINITION_VERSION"]),
]


# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------
def _load_json(path: Path):
    try:
        return json.loads(path.read_text())
    except FileNotFoundError:
        return None


def _fmt(v):
    """Render a scalar/list config value for a Markdown table cell."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "null"
    if isinstance(v, list):
        return ", ".join(_fmt(x) for x in v)
    return str(v)


def _flatten(d, prefix=""):
    """Flatten a nested config dict to [(dotted.path, rendered_value)], skipping `_comment_*`."""
    rows = []
    for k, v in d.items():
        if isinstance(k, str) and k.startswith("_comment"):
            continue
        path = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            rows.extend(_flatten(v, path))
        else:
            rows.append((path, _fmt(v)))
    return rows


def _md_table(header, rows):
    if not rows:
        return "_(none)_\n"
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out) + "\n"


def _rate_str(num, den):
    if not den:
        return "n/a"
    return f"{num:,} / {den:,} = {100 * num / den:.1f}%"


# ---------------------------------------------------------------------------
# per-metric AUTOGEN block
# ---------------------------------------------------------------------------
def _headline_all(feed):
    """(num, den) for the __ALL__ / all-time headline cell, or (None, None)."""
    cell = (feed.get("headline", {}).get("cells", {}).get("__ALL__", {}) or {}).get("all")
    if not cell:
        return None, None
    return cell.get("num"), cell.get("den")


def _provenance_rows(feed):
    prov = feed.get("provenance") or {}
    if prov:
        return [
            ("definition_version", prov.get("definition_version", "—")),
            ("code_version (git SHA)", prov.get("code_version", "—")),
            ("clif_version", prov.get("clif_version", "—")),
            ("site_id", prov.get("site_id", "—")),
            ("generated", prov.get("generated", "—")),
        ]
    # graceful degrade: no provenance block yet — fall back to the feed's top-level generated
    return [
        ("definition_version", "n/a (no provenance block)"),
        ("code_version (git SHA)", "n/a"),
        ("clif_version", "n/a"),
        ("site_id", "n/a"),
        ("generated", feed.get("generated", "—")),
    ]


def _lpv_constant_rows():
    rows = []
    for rel, names in LPV_CONSTANT_SOURCES:
        text = (ROOT / rel).read_text() if (ROOT / rel).exists() else ""
        for name in names:
            m = re.search(rf"^\s*{re.escape(name)}\s*=\s*([^\s#]+)", text, re.MULTILINE)
            val = m.group(1).strip().strip('"').strip("'") if m else "(see code)"
            rows.append((name, val, f"`{rel}`"))
    return rows


def _knob_section(metric):
    """Markdown for the definitional-knob table + any `_comment_*` doc strings."""
    if metric == "lpv":
        rows = _lpv_constant_rows()
        return ("**Definitional constants** (LPV has no `config.json`; scraped from the pipeline code — "
                "the tile headline uses Vt ≤ `SCORECARD_VT_CUTOFF`, the pipeline default is Vt ≤ "
                "`VT_MAX_DEFAULT`):\n\n"
                + _md_table(["Constant", "Value", "Source"], rows))

    cfg = _load_json(CONFIG_PATH[metric])
    if cfg is None:
        return "_config.json not found — knobs unavailable._\n"

    # `_comment_*` doc strings, rendered verbatim as blockquote notes (definition provenance in prose).
    comments = []
    for k, v in cfg.items():
        if isinstance(k, str) and k.startswith("_comment") and isinstance(v, str):
            comments.append(f"> **{k}** — {v}")

    rows = []
    for k, v in cfg.items():
        if k in CONFIG_PLUMBING or (isinstance(k, str) and k.startswith("_comment")):
            continue
        if isinstance(v, dict):
            rows.extend(_flatten(v, k))
        else:
            rows.append((k, _fmt(v)))
    rows = [(f"`{p}`", val) for p, val in rows]

    out = f"**Definitional parameters** (from `{CONFIG_PATH[metric].relative_to(ROOT)}`):\n\n"
    out += _md_table(["Parameter", "Value"], rows)
    if comments:
        out += "\n**Config documentation strings** (verbatim):\n\n" + "\n\n".join(comments) + "\n"
    return out


def metric_autogen(metric, feed):
    num, den = _headline_all(feed)
    hl = feed.get("headline", {})
    grain = feed.get("grain", {})
    units = grain.get("units", [])
    periods = grain.get("periods", [])
    segs = feed.get("segments", []) or []
    note = feed.get("note")

    lines = [STAMP_NOTICE, ""]
    lines.append(f"**Tile:** {feed.get('title', metric)} — {feed.get('subtitle', '')}  ")
    lines.append(f"**Drill-down:** `{feed.get('detail_href', '—')}`")
    lines.append("")
    lines.append("**Current headline (all units · all time):** "
                 f"{hl.get('label', 'numerator')} = {_rate_str(num, den)} "
                 f"({hl.get('den_label', '')}; n_unit = {hl.get('n_unit', '')})")
    if feed.get("goal") is not None:
        lines.append(f"  · goal line: {100 * feed['goal']:.0f}%")
    lines.append("")

    lines.append("**Provenance:**")
    lines.append("")
    lines.append(_md_table(["Field", "Value"], _provenance_rows(feed)))

    lines.append("**Grain published to the scorecard:**")
    lines.append("")
    lines.append(f"- Units ({len(units)}): {', '.join(f'`{u}`' for u in units)}")
    lines.append(f"- Periods: {', '.join(f'`{p}`' for p in periods)}")
    if segs:
        lines.append(f"- Segments: {', '.join(s.get('label', s.get('key', '?')) for s in segs)}")
    lines.append("")

    lines.append(_knob_section(metric))

    if note:
        lines.append("**Tile caveat note (shown on the scorecard):**")
        lines.append("")
        lines.append("> " + note.replace("\n", "\n> "))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# index + scorecard-level AUTOGEN blocks
# ---------------------------------------------------------------------------
def index_autogen(metrics, feeds):
    rows = []
    for m in metrics:
        feed = feeds.get(m)
        if not feed:
            rows.append((f"`{m}`", "—", "_(feed missing)_", "—"))
            continue
        num, den = _headline_all(feed)
        prov = feed.get("provenance") or {}
        gen = prov.get("generated") or feed.get("generated", "—")
        rows.append((
            f"**{feed.get('title', m)}**",
            _rate_str(num, den),
            f"[`metrics/{m}/METHODS.md`](../metrics/{m}/METHODS.md)",
            gen,
        ))
    out = [STAMP_NOTICE, ""]
    out.append(_md_table(["Tile", "Headline (all · all time)", "Methods doc", "Data generated"], rows))
    return "\n".join(out).rstrip() + "\n"


def scorecard_autogen(metrics, feeds):
    lines = [STAMP_NOTICE, ""]
    lines.append(f"**Enabled metrics** (`config.json → metrics`, rendered left→right): "
                 f"{', '.join(f'`{m}`' for m in metrics)}")
    lines.append("")
    lines.append("**Feed discovery (by convention):** for each enabled metric `<m>`, the combiner reads "
                 "`metrics/<m>/output/final/tile_feed_<m>.json` (`load_feed`, `scorecard/build_scorecard.py`). "
                 "There is no `scorecard_tiles` registry key — it was retired in the monorepo move.")
    lines.append("")
    lines.append("**Per-tile grain published today:**")
    lines.append("")
    rows = []
    for m in metrics:
        feed = feeds.get(m)
        if not feed:
            continue
        g = feed.get("grain", {})
        rows.append((f"`{m}`", str(len(g.get("units", []))), ", ".join(f"`{p}`" for p in g.get("periods", []))))
    lines.append(_md_table(["Metric", "# units", "Periods"], rows))
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# splice
# ---------------------------------------------------------------------------
def splice(path: Path, block: str, stub_header: str) -> str:
    """Replace the text between the AUTOGEN markers in `path` with `block`.

    If the file is absent, create it from `stub_header` (hand-editable prose) + the markers.
    Returns "created" | "updated" | "unchanged".
    """
    wrapped = f"{START}\n\n{block}\n{END}"
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(stub_header.rstrip() + "\n\n" + wrapped + "\n")
        return "created"

    text = path.read_text()
    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), wrapped, text, count=1, flags=re.DOTALL)
    else:
        new = text.rstrip() + "\n\n" + wrapped + "\n"
    if new == text:
        return "unchanged"
    path.write_text(new)
    return "updated"


def _stub(title: str, intro: str) -> str:
    return (f"# {title}\n\n{intro}\n\n"
            "> _Prose above the AUTOGEN block is hand-written; edit it freely. "
            "The stamped facts below refresh from the pipeline on every scorecard rebuild._\n")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main() -> int:
    root_cfg = _load_json(ROOT / "config.json") or {}
    metrics = root_cfg.get("metrics", [])
    if not metrics:
        print("[methods] no metrics enabled in config.json — nothing to do", file=sys.stderr)
        return 1

    feeds = {}
    for m in metrics:
        feed = _load_json(ROOT / "metrics" / m / "output" / "final" / f"tile_feed_{m}.json")
        if feed is not None:
            feeds[m] = feed

    # Build every (path, generated-block, stub) target first, so the PHI guard can vet the
    # machine-generated blocks BEFORE anything is written. Only the AUTOGEN block is checked — the
    # hand-written prose is a data dictionary and legitimately names schema columns like
    # `hospitalization_id`, which are identifiers, not identifier *values*.
    targets = []  # (rel_path, abs_path, block, stub)

    for m in metrics:
        feed = feeds.get(m)
        if feed is None:
            print(f"[methods] {m}: tile feed missing — skipped (run its pipeline first)")
            continue
        stub = _stub(f"{feed.get('title', m)} — Methods",
                     f"Methods & data-dictionary reference for the **{feed.get('title', m)}** scorecard tile. "
                     "See the sibling `CLAUDE.md` for implementation detail.")
        targets.append((f"metrics/{m}/METHODS.md", ROOT / "metrics" / m / "METHODS.md",
                        metric_autogen(m, feed), stub))

    idx_stub = _stub("CLIF Ventilator QI Bundle — Methods Index",
                     "Living methods / data-dictionary reference for every component of the QI bundle "
                     "scorecard. Each tile has its own methods doc; the combiner has one too.\n\n"
                     "- Combiner: [`scorecard_methods.md`](scorecard_methods.md)\n"
                     "- Tile-feed contract: [`../contract/tile_feed_contract.md`](../contract/tile_feed_contract.md)")
    targets.append(("docs/README.md", DOCS / "README.md", index_autogen(metrics, feeds), idx_stub))

    sc_stub = _stub("Bundle Scorecard — Methods",
                    "How the bundle scorecard (`scorecard/build_scorecard.py`) assembles the per-metric "
                    "tiles, and its grain-fallback / unit-grouping rules.")
    targets.append(("docs/scorecard_methods.md", DOCS / "scorecard_methods.md",
                    scorecard_autogen(metrics, feeds), sc_stub))

    # PHI guard — vet the machine-generated blocks (from config + feeds) before writing.
    for rel, _abs, block, _tmpl in targets:
        hits = [s for s in PHI_FORBIDDEN if s in block]
        if hits:
            print(f"[methods] ABORT — PHI substring(s) {hits} in the generated block for {rel}",
                  file=sys.stderr)
            return 2

    print("[methods] refreshed living methods docs:")
    for rel, abs_path, block, stub in targets:
        status = splice(abs_path, block, stub)
        print(f"  {status:9} {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
